---
title: Smartphone Processors Ranking & Scores
author: Tomasz Dąbkowski
output: flexdashboard::flex_dashboard
---

```{r setup, warning=F}
library(tidyverse)
library(rmarkdown)
library(knitr)

cpus <- read_csv("ML_ALL_benchmarks.csv")
opts_chunk$set(fig.width = 5, fig.asp = 1/2)
```
# Dashboard

## Column 1

###  Top CPU Performance
```{r}
kable(
    cpus %>%
        select(company, device, cpuName, cpuScore) %>%
        arrange(desc(cpuScore)) %>%
        head(10)
)
```

###  Top GPU Performance
```{r}
kable(
    cpus %>%
        select(company, device, cpuName, gpuScore) %>%
        arrange(desc(gpuScore)) %>%
        head(10)
)
```

###  Top TPU Performance
```{r}
kable(
    cpus %>%
        select(company, device, cpuName, npuScore) %>%
        arrange(desc(npuScore)) %>%
        head(10)
)
```

### Top Performance by Producent
```{r}
performance_pivot <- cpus %>%
    group_by(company) %>%
    summarize(averageCPUPerformance = mean(cpuScore),
              averageGPUPerformance = mean(gpuScore),
              averageNPUPerformance = mean(npuScore))

kable(performance_pivot)
```

## Column 2

### Clock Speed Distribution
```{r}
ggplot(cpus, mapping = aes(x = clock)) +
    geom_histogram(binwidth = 500) +
    xlab("Clock speed")
```

### Core Count Distribution
```{r}
ggplot(cpus, mapping = aes(x = cores)) +
    geom_histogram(binwidth = 1) +
    xlab("Number of Cores") 
```

# Quick summary

### Quick summary
```{r}
summary(cpus)
```
